- name:
  set_fact:
    join_command: "{{ hostvars[kubernetes.cluster.master_node.name].join_command }}"
  when: 
    - "join_command is not defined"
    - "hostvars[kubernetes.cluster.master_node.name].join_command is defined"
    
- name: Join the node to the cluster
  shell: "{{ join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
  when: 
    - "join_command is defined"
