- name: Get cluster join command
  become: yes
  become_user: "{{ kubernetes.cluster.k8s_user.username }}"
  shell: kubeadm token create --print-join-command
  register: kube_join_command
  run_once: true
  delegate_to: "{{ kubernetes.cluster.master_node.name }}"
  tags:
    - clusterjoin

- block: 
  - name: Join the node to the cluster
    shell: "{{ kube_join_command.stdout }} >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt
    when: 
      - "kube_join_command is defined"
    tags:
      - clusterjoin
  rescue:
  - name: Delete flag file
    file:
      path: $HOME/node_joined.txt
      state: absent
  - fail:
      msg: "Could not join node to cluster"
