- name: Execute all package related tasks
  import_tasks: packages.yml
  tags:
    - k8s-worker
    - packages 

- name: Execute all system related tasks
  import_tasks: system.yml
  tags:
    - k8s-worker
    - system

- name: Execute all iptables related tasks
  import_tasks: iptables.yml
  tags:
    - k8s-worker
  when:
    - kubernetes.cluster.feature_toggles.glusterfs

- name: Join worker node to cluster
  import_tasks: cluster-join.yml
  tags:
    - k8s-worker
    - cluster
