- name: Run kubeadm for initialization
  shell: |
    kubeadm init \
      --pod-network-cidr={{ kubernetes.cluster.network.cidr }} \
      >> cluster-phase1.initialized
  args:
    chdir: $HOME
    creates: cluster-phase1.initialized

- name: Create .kube directory for kube user
  become: yes
  become_user: "{{ kubernetes.cluster.k8s_user.username }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to kube user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ kubernetes.cluster.k8s_user.username }}/.kube/config"
    remote_src: yes
    owner: kube

#- name: Wait a few seconds for Kubernetes changes to propagate
#  pause:
#    seconds: 30
#
#- name: Wait for Cluster to be initialized fully (600s timeout)
#  become: yes
#  become_user: "{{ kubernetes.cluster.k8s_user.username }}"
#  shell: "kubectl get pods -n kube-system -o=wide | grep -v NAME | awk '{ print $2 }'"
#  register: kubernetes_initialized
#  until: "'0/1' not in kubernetes_initialized.stdout_lines"
#  delay: 20
#  retries: 30
