- name: Run kubeadm for initialization
  shell: |
    kubeadm init \
      --pod-network-cidr={{ kubernetes.features.flannel.network }} \
      >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: Create .kube directory for kube user
  become: yes
  become_user: "{{ kubernetes.cluster.k8s_user.username }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to kube user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ kubernetes.cluster.k8s_user.username }}/.kube/config"
    remote_src: yes
    owner: kube


