---

- name: Ensure descriptors directory exists on master node
  become: yes
  become_user: "{{ kubernetes.cluster.k8s_user.username }}"
  file:
    path: $HOME/descriptors/flannel
    state: directory
    mode: 0700

- name: Copy Kubernetes flannel config to master node
  become: yes
  become_user: "{{ kubernetes.cluster.k8s_user.username }}"
  template:
    src: features/flannel/kube-flannel.yml
    dest: $HOME/descriptors/flannel/kube-flannel.yml

- name: Initialize Kubernetes flannel network config
  become: yes
  become_user: "{{ kubernetes.cluster.k8s_user.username }}"
  k8s:
    src: $HOME/descriptors/flannel/kube-flannel.yml
    state: present
