- name: Install required packages
  import_tasks: packages.yml
  tags:
    - packages

- name: Initialize Kubernetes cluster
  import_tasks: cluster-init.yml
  tags:
    - cluster

- name: Include Flannel networking tasks
  import_tasks: flannel.yml
  when:
    - "kubernetes.cluster.network.type == 'flannel'"
  tags:
    - cluster
    - network
    - flannel

