---
- name: Install required packages
  yum:
    name: [ python2-pip, heketi-client ]
    state: installed

- name: Upgrade Python setuptools
  pip:
    name: setuptools
    state: latest
  environment:
    http_proxy: "{{ kubernetes.docker.http_proxy | default('') }}"
    https_proxy: "{{ kubernetes.docker.http_proxy | default('') }}"

- name: Install Python openshift package
  pip:
    name: openshift
    state: present
  environment:
    http_proxy: "{{ kubernetes.docker.http_proxy | default('') }}"
    https_proxy: "{{ kubernetes.docker.http_proxy | default('') }}"
