---
- name: Include MetalLB setup tasks
  import_tasks: metallb.yml
  when:
    - "kubernetes.cluster.feature_toggles.metallb"
  tags:
    - cluster
    - features
    - metallb

- name: Include Heketi bootstrap setup tasks
  import_tasks: heketi-bootstrap.yml
  when:
    - "kubernetes.cluster.feature_toggles.glusterfs"
  tags:
    - cluster
    - features
    - glusterfs
